apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: backstage-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: backstage-

resources:
- ../../crd
- ../../rbac
- manager.yaml

patches:
- path: manager_auth_proxy_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
#      name: controller-manager
#      namespace: system

images:
- name: controller
  newName: quay.io/rhdh-community/operator
  newTag: 0.4.0@sha256:ccb20fc53bcf8d0843f8ae040971c381363027c73a1f168203565aa060ba9294

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
- files:
  - default-config/app-config.yaml
  - default-config/db-secret.yaml
  - default-config/db-service.yaml
  - default-config/db-statefulset.yaml
  - default-config/deployment.yaml
  - default-config/service.yaml
  name: default-config
